spring:
  application:
    name: homework13
  datasource:
    name: postgres
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  redis:
    host: localhost
    port: 6379
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  session:
    store-type: jdbc

server:
  servlet:
    session:
      timeout: 600

executor:
  fixed-thread-pool-size: 3
  scheduled-thread-pool-size: 3
  schedule-duration: PT1H