spring:
  application:
    name: homework13
  datasource:
    name: postgres
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: db.changelog/db.changelog-master.xml

services:
  kudago-service:
    max-concurrent-requests: 5

executor:
  fixed-thread-pool-size: 3
  scheduled-thread-pool-size: 3
  schedule-duration: PT1H